"""Initial migration: create sessions, signals, frames tables

Revision ID: 14ac193f0a78
Revises: 
Create Date: 2025-09-25 17:38:20.367099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ac193f0a78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('car_id', sa.String(length=100), nullable=True),
    sa.Column('driver', sa.String(length=100), nullable=True),
    sa.Column('track', sa.String(length=100), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_car_id', 'sessions', ['car_id'], unique=False)
    op.create_index('ix_sessions_created_utc', 'sessions', ['created_utc'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ts_mono_ns', sa.BigInteger(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frames_id'), 'frames', ['id'], unique=False)
    op.create_index('ix_frames_session_id', 'frames', ['session_id'], unique=False)
    op.create_index('ix_frames_ts_mono_ns', 'frames', ['ts_mono_ns'], unique=False)
    op.create_index('ix_frames_ts_utc', 'frames', ['ts_utc'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ts_mono_ns', sa.BigInteger(), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quality', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index('ix_signals_session_id', 'signals', ['session_id'], unique=False)
    op.create_index('ix_signals_session_source', 'signals', ['session_id', 'source'], unique=False)
    op.create_index('ix_signals_source_channel', 'signals', ['source', 'channel'], unique=False)
    op.create_index('ix_signals_ts_mono_ns', 'signals', ['ts_mono_ns'], unique=False)
    op.create_index('ix_signals_ts_utc', 'signals', ['ts_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_ts_utc', table_name='signals')
    op.drop_index('ix_signals_ts_mono_ns', table_name='signals')
    op.drop_index('ix_signals_source_channel', table_name='signals')
    op.drop_index('ix_signals_session_source', table_name='signals')
    op.drop_index('ix_signals_session_id', table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_frames_ts_utc', table_name='frames')
    op.drop_index('ix_frames_ts_mono_ns', table_name='frames')
    op.drop_index('ix_frames_session_id', table_name='frames')
    op.drop_index(op.f('ix_frames_id'), table_name='frames')
    op.drop_table('frames')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index('ix_sessions_created_utc', table_name='sessions')
    op.drop_index('ix_sessions_car_id', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
