"""add device profiles and setup models

Revision ID: 37467b2aefe1
Revises: 14ac193f0a78
Create Date: 2025-09-25 23:17:55.644713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37467b2aefe1'
down_revision: Union[str, None] = '14ac193f0a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gps_config', sa.JSON(), nullable=True),
    sa.Column('obd_config', sa.JSON(), nullable=True),
    sa.Column('meshtastic_config', sa.JSON(), nullable=True),
    sa.Column('custom_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_profiles_default', 'device_profiles', ['is_default'], unique=False)
    op.create_index(op.f('ix_device_profiles_id'), 'device_profiles', ['id'], unique=False)
    op.create_table('device_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('setup_type', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('port_path', sa.String(length=255), nullable=True),
    sa.Column('baud_rate', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['device_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_setup_profile', 'device_setup', ['profile_id'], unique=False)
    op.create_index('idx_device_setup_status', 'device_setup', ['status'], unique=False)
    op.create_index('idx_device_setup_type', 'device_setup', ['setup_type'], unique=False)
    op.create_index(op.f('ix_device_setup_id'), 'device_setup', ['id'], unique=False)
    op.create_index(op.f('ix_device_setup_profile_id'), 'device_setup', ['profile_id'], unique=False)
    op.alter_column('frames', 'ts_utc',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('frames', 'ts_mono_ns',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index('idx_frames_session_ts', 'frames', ['session_id', 'ts_utc'], unique=False)
    op.add_column('sessions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('sessions', sa.Column('started_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('stopped_utc', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('sessions', 'driver',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('sessions', 'track',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('ix_sessions_car_id', table_name='sessions')
    op.drop_index('ix_sessions_created_utc', table_name='sessions')
    op.drop_column('sessions', 'notes')
    op.alter_column('signals', 'ts_utc',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('signals', 'ts_mono_ns',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('signals', 'value_text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('signals', 'quality',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_index('ix_signals_session_source', table_name='signals')
    op.drop_index('ix_signals_source_channel', table_name='signals')
    op.create_index('idx_signals_session_channel', 'signals', ['session_id', 'channel'], unique=False)
    op.create_index('idx_signals_session_source', 'signals', ['session_id', 'source'], unique=False)
    op.create_index('idx_signals_ts_utc', 'signals', ['ts_utc'], unique=False)
    op.create_index(op.f('ix_signals_channel'), 'signals', ['channel'], unique=False)
    op.create_index(op.f('ix_signals_source'), 'signals', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_source'), table_name='signals')
    op.drop_index(op.f('ix_signals_channel'), table_name='signals')
    op.drop_index('idx_signals_ts_utc', table_name='signals')
    op.drop_index('idx_signals_session_source', table_name='signals')
    op.drop_index('idx_signals_session_channel', table_name='signals')
    op.create_index('ix_signals_source_channel', 'signals', ['source', 'channel'], unique=False)
    op.create_index('ix_signals_session_source', 'signals', ['session_id', 'source'], unique=False)
    op.alter_column('signals', 'quality',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('signals', 'value_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('signals', 'ts_mono_ns',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('signals', 'ts_utc',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.add_column('sessions', sa.Column('notes', sa.TEXT(), nullable=True))
    op.create_index('ix_sessions_created_utc', 'sessions', ['created_utc'], unique=False)
    op.create_index('ix_sessions_car_id', 'sessions', ['car_id'], unique=False)
    op.alter_column('sessions', 'track',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('sessions', 'driver',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('sessions', 'stopped_utc')
    op.drop_column('sessions', 'started_utc')
    op.drop_column('sessions', 'is_active')
    op.drop_index('idx_frames_session_ts', table_name='frames')
    op.alter_column('frames', 'ts_mono_ns',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('frames', 'ts_utc',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_device_setup_profile_id'), table_name='device_setup')
    op.drop_index(op.f('ix_device_setup_id'), table_name='device_setup')
    op.drop_index('idx_device_setup_type', table_name='device_setup')
    op.drop_index('idx_device_setup_status', table_name='device_setup')
    op.drop_index('idx_device_setup_profile', table_name='device_setup')
    op.drop_table('device_setup')
    op.drop_index(op.f('ix_device_profiles_id'), table_name='device_profiles')
    op.drop_index('idx_device_profiles_default', table_name='device_profiles')
    op.drop_table('device_profiles')
    # ### end Alembic commands ###
